name: macura_env_gymnasium_hpc_compatible
channels:
  - pytorch
  - menpo
  - anaconda
  - nvidia
  - conda-forge
  - nodefaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _sysroot_linux-64_curr_repodata_hack=3=haa98f57_10
  - aom=3.9.1=hac33072_0
  - binutils_impl_linux-64=2.38=h2a08ee3_1
  - binutils_linux-64=2.38.0=hc2dff05_0
  - blas=1.0=mkl
  - brotli-python=1.0.9=py311h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.33.0=ha66036c_0
  - ca-certificates=2024.7.4=hbcca054_0
  - cairo=1.18.0=hebfffa5_3
  - certifi=2024.7.4=py311h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cuda-cccl=12.4.127=0
  - cuda-cudart=12.4.127=0
  - cuda-cudart-dev=12.4.127=0
  - cuda-cudart-static=12.4.127=0
  - cuda-cupti=12.4.127=0
  - cuda-libraries=12.4.0=0
  - cuda-nvcc=12.4.131=0
  - cuda-nvcc_linux-64=12.4.1=0
  - cuda-nvrtc=12.4.127=0
  - cuda-nvtx=12.4.127=0
  - cuda-opencl=12.4.127=0
  - cuda-runtime=12.4.0=0
  - cuda-version=11.8=hcce14f8_3
  - cudatoolkit=11.8.0=h6a678d5_0
  - dav1d=1.2.1=h5eee18b_0
  - elfutils=0.191=h924a536_0
  - expat=2.6.2=h6a678d5_0
  - ffmpeg=7.0.2=gpl_h0db5852_100
  - filelock=3.13.1=py311h06a4308_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h7b6447c_0
  - gcc_impl_linux-64=11.2.0=h1234567_1
  - gcc_linux-64=11.2.0=h5c386dc_0
  - gettext=0.22.5=he02047a_3
  - gettext-tools=0.22.5=he02047a_3
  - glew=2.1.0=h9c3ff4c_2
  - glfw3=3.2.1=0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.1.2=py311hc9b5ff0_0
  - gnutls=3.7.9=hb077bed_0
  - graphite2=1.3.14=h295c915_1
  - gxx_impl_linux-64=11.2.0=h1234567_1
  - gxx_linux-64=11.2.0=hc2dff05_0
  - harfbuzz=9.0.0=hda332d3_1
  - icu=75.1=he02047a_0
  - idna=3.7=py311h06a4308_0
  - intel-openmp=2022.0.1=h06a4308_3633
  - jinja2=3.1.4=py311h06a4308_0
  - kernel-headers_linux-64=3.10.0=h57e8cba_10
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=4.0.0=h27087fc_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libarchive=3.7.4=hfca40fe_0
  - libasprintf=0.22.5=he8f35ee_3
  - libasprintf-devel=0.22.5=he8f35ee_3
  - libass=0.17.3=h1dc1e6a_0
  - libblas=3.9.0=16_linux64_mkl
  - libcblas=3.9.0=16_linux64_mkl
  - libcublas=12.4.2.65=0
  - libcufft=11.2.0.44=0
  - libcufile=1.9.1.3=0
  - libcurand=10.3.5.147=0
  - libcurl=8.9.1=hdb1bdb2_0
  - libcusolver=11.6.0.99=0
  - libcusparse=12.3.0.142=0
  - libdeflate=1.21=h4bc722e_0
  - libdrm=2.4.122=h4ab18f5_0
  - libdrm-cos6-x86_64=2.4.65=4
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libexpat=2.6.2=h59595ed_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-devel_linux-64=11.2.0=h1234567_1
  - libgcc-ng=14.1.0=h77fa898_0
  - libgettextpo=0.22.5=he02047a_3
  - libgettextpo-devel=0.22.5=he02047a_3
  - libglib=2.80.3=h315aac3_2
  - libglu=9.0.0=he1b5a44_1001
  - libgomp=14.1.0=h77fa898_0
  - libhwloc=2.11.1=default_hecaa2ac_1000
  - libiconv=1.17=hd590300_2
  - libidn2=2.3.7=hd590300_0
  - libjpeg-turbo=3.0.3=h5eee18b_0
  - liblapack=3.9.0=16_linux64_mkl
  - libllvm18=18.1.8=h8b73ec9_2
  - libmicrohttpd=1.0.1=h97afed2_0
  - libnghttp2=1.58.0=h47da74e_1
  - libnpp=12.2.5.2=0
  - libnsl=2.0.1=hd590300_0
  - libnvfatbin=12.4.127=0
  - libnvjitlink=12.4.99=0
  - libnvjpeg=12.3.1.89=0
  - libopenvino=2024.3.0=h2da1b83_0
  - libopenvino-auto-batch-plugin=2024.3.0=hb045406_0
  - libopenvino-auto-plugin=2024.3.0=hb045406_0
  - libopenvino-hetero-plugin=2024.3.0=h5c03a75_0
  - libopenvino-intel-cpu-plugin=2024.3.0=h2da1b83_0
  - libopenvino-intel-gpu-plugin=2024.3.0=h2da1b83_0
  - libopenvino-intel-npu-plugin=2024.3.0=h2da1b83_0
  - libopenvino-ir-frontend=2024.3.0=h5c03a75_0
  - libopenvino-onnx-frontend=2024.3.0=h07e8aee_0
  - libopenvino-paddle-frontend=2024.3.0=h07e8aee_0
  - libopenvino-pytorch-frontend=2024.3.0=he02047a_0
  - libopenvino-tensorflow-frontend=2024.3.0=h39126c6_0
  - libopenvino-tensorflow-lite-frontend=2024.3.0=he02047a_0
  - libopus=1.3.1=h7b6447c_0
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.43=h2797004_0
  - libprotobuf=4.25.3=h08a7969_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-devel_linux-64=11.2.0=h1234567_1
  - libstdcxx-ng=14.1.0=hc0a3c3a_0
  - libtasn1=4.19.0=h166bdaf_0
  - libtiff=4.6.0=h46a8edc_4
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libva=2.22.0=hb711507_0
  - libvpx=1.14.1=hac33072_0
  - libwebp-base=1.4.0=hd590300_0
  - libx11-common-cos6-x86_64=1.6.4=4
  - libx11-cos6-x86_64=1.6.4=4
  - libxcb=1.16=hd590300_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.12.7=he7c6b58_4
  - libzlib=1.3.1=h4ab18f5_1
  - llvm-openmp=15.0.7=h0cdce71_0
  - lz4-c=1.9.4=hcb278e6_0
  - lzo=2.10=hd590300_1001
  - markupsafe=2.1.3=py311h5eee18b_0
  - mesa-libgl-cos6-x86_64=11.0.7=4
  - mesalib=24.1.5=h3ac77ca_0
  - mkl=2022.1.0=hc2b9512_224
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py311h06a4308_0
  - ncurses=6.5=h59595ed_0
  - nettle=3.9.1=h7ab15ed_0
  - networkx=3.3=py311h06a4308_0
  - numpy=1.26.4=py311h64a7726_0
  - ocl-icd=2.3.2=h5eee18b_1
  - openh264=2.4.1=h59595ed_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.3.1=h4bc722e_2
  - p11-kit=0.24.1=hc5aa10d_0
  - pcre2=10.44=hba22ea6_2
  - pillow=10.4.0=py311h82a398c_0
  - pip=24.2=py311h06a4308_0
  - pixman=0.43.2=h59595ed_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pugixml=1.14=h59595ed_0
  - pysocks=1.7.1=py311h06a4308_0
  - python=3.11.9=hb806964_0_cpython
  - python_abi=3.11=4_cp311
  - pytorch=2.4.0=py3.11_cuda12.4_cudnn9.1.0_0
  - pytorch-cuda=12.4=hc786d27_6
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py311h06a4308_0
  - setuptools=72.1.0=py311h06a4308_0
  - snappy=1.2.1=h6a678d5_0
  - sqlite=3.46.0=h6d4b2fc_0
  - svt-av1=2.1.2=hac33072_0
  - swig==4.2.1 
  - sympy=1.12=py311h06a4308_0
  - sysroot_linux-64=2.17=h57e8cba_10
  - tbb=2021.12.0=h434a139_3
  - tk=8.6.13=noxft_h4845f30_101
  - torchaudio=2.4.0=py311_cu124
  - torchtriton=3.0.0=py311
  - torchvision=0.19.0=py311_cu124
  - typing_extensions=4.11.0=py311h06a4308_0
  - urllib3=2.2.2=py311h06a4308_0
  - wayland=1.23.0=h5291e77_0
  - wayland-protocols=1.36=hd8ed1ab_0
  - wheel=0.43.0=py311h06a4308_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xorg-damageproto=1.2.1=h7f98852_1002
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-glproto=1.4.17=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.9=hb711507_1
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdamage=1.1.5=h7f98852_1
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxrandr=1.5.2=h7f98852_1
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-randrproto=1.5.0=h7f98852_1001
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-util-macros=1.19.3=h7f98852_0
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xf86vidmodeproto=2.3.1=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.3.1=h4ab18f5_1
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - absl-py==2.1.0
      - antlr4-python3-runtime==4.9.3
      - appmap==2.1.7
      - box2d-py==2.3.5
      - cffi==1.17.0
      - click==8.1.7
      - cloudpickle==3.0.0
      - colorednoise==2.2.0
      - contourpy==1.2.1
      - cycler==0.12.1
      - cython==0.29.37
      - distlib==0.3.8
      - docker-pycreds==0.4.0
      - etils==1.9.2
      - farama-notifications==0.0.4
      - fasteners==0.19
      - fonttools==4.53.1
      - fsspec==2024.6.1
      - gitdb==4.0.11
      - gitpython==3.1.43
      - glfw==2.7.0
      - grpcio==1.65.4
      - gym-notices==0.0.8
      - gymnasium==0.29.1
      - hydra-core==1.3.2
      - imageio==2.35.0
      - importlib-resources==5.13.0
      - inflection==0.5.1
      - kiwisolver==1.4.5
      - markdown==3.6
      - matplotlib==3.9.2
      - mujoco==2.3.7
      - omegaconf==2.3.0
      - opencv-python==4.10.0.84
      - packaging==24.1
      - pandas==2.2.2
      - platformdirs==4.2.2
      - plotly==5.23.0
      - protobuf==5.27.3
      - psutil==6.0.0
      - pycparser==2.22
      - pygame==2.6.0
      - pyopengl==3.1.7
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyyaml==6.0.2
      - scipy==1.14.0
      - seaborn==0.13.2
      - sentry-sdk==2.13.0
      - setproctitle==1.3.3
      - six==1.16.0
      - smmap==5.0.1
      - tenacity==9.0.0
      - tensorboard==2.17.1
      - tensorboard-data-server==0.7.2
      - termcolor==2.4.0
      - tqdm==4.66.5
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - virtualenv==20.26.3
      - wandb==0.17.6
      - werkzeug==3.0.3
      - zipp==3.20.0
variables:
  MUJOCO_GL: egl
  PYOPENGL_PLATFORM: egl
prefix: /root/miniconda3/envs/macura_env_gymnasium_hpc_compatible